experiment_name: "diff_mouse_base"
seed: 1337

data:
  dataset_id: "balabit"
  sequence_length: 64
  batch_size: 32
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  train_split: "train"
  val_split: "val"
  max_train_gestures: null
  max_val_gestures: 256
  normalize_sequences: true
  normalize_features: true
  canonicalize_path: false
  canonicalize_duration: false
  include_goal_geometry: false
  feature_mode: "neuromotor"
  sampling_rate: "auto"
  time_stretch: 0.15
  jitter_std: 0.02
  mirror_prob: 0.5
  max_channel_std: 10.0
  max_delta_abs: 5000.0
  outlier_log_limit: 5

model:
  in_channels: 3
  out_channels: 3
  base_channels: 128
  channel_mults: [1.0, 1.5, 2.0, 2.0]
  num_res_blocks: 2
  dropout: 0.1
  norm_groups: 32
  use_attention: true
  attn_heads: 4
  self_condition: true
  cond_dim: 0
  time_embed_dim: null

diffusion:
  timesteps: 1000
  schedule: "cosine"

training:
  epochs: 10
  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.001
  ema_decay: 0.9995
  grad_clip: 1.0
  amp: false
  log_interval: 50
  eval_interval: 1
  checkpoint_dir: "checkpoints/diffusion"
  checkpoint_interval: 5
  eval_classifier: true
  classifier_samples: 2048
  classifier_steps: 50
  balance_time_steps: true
  time_weight_max: 4.0
  scale_reg_weight: 0.2
  scale_reg_channels: [0, 1]
  path_length_reg_weight: 0.1
  direction_change_reg_weight: 0.0
  curvature_reg_weight: 0.0
  direction_change_reg_warmup_epochs: 5
  curvature_reg_warmup_epochs: 5
  loss_skip_threshold: null
  log_loss_details: false
  eval_path_scale_min: 0.05
  eval_path_scale_max: 4.0
  timing_eval:
    enabled: true
    checkpoint_path: "checkpoints/timing/timing_model.pt"
    cache_dir: datasets
    dataset_id: "balabit"
    split: train
    temperature: 1.0
    profile_mix: 0.5
    duration_mix: 0.25
    clip_quantile: 0.94
    clip_multiplier: 1.002
    max_duration: null
    min_profile_value: 0.0001
  eval_prep:
    force_deltas_when_missing_dt: true
    clamp_delta_t: true
    clamp_percentile: 0.5
    clamp_value: null
    log_batch_stats: true
    match_length_distribution: true
